// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_cep_study/test/feature/number_trivia/data/models/repositories/address_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_cep_study/core/platform/network_info.dart' as _i6;
import 'package:flutter_cep_study/features/adress_by_cep/data/datasources/address_local_data_source.dart'
    as _i5;
import 'package:flutter_cep_study/features/adress_by_cep/data/datasources/address_remote_data_source.dart'
    as _i3;
import 'package:flutter_cep_study/features/adress_by_cep/data/models/address_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAddressModel_0 extends _i1.Fake implements _i2.AddressModel {}

/// A class which mocks [AddressRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRemoteDataSource extends _i1.Mock
    implements _i3.AddressRemoteDataSource {
  MockAddressRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AddressModel> getAddressByCep(String? cep) =>
      (super.noSuchMethod(Invocation.method(#getAddressByCep, [cep]),
              returnValue:
                  Future<_i2.AddressModel>.value(_FakeAddressModel_0()))
          as _i4.Future<_i2.AddressModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AddressLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressLocalDataSource extends _i1.Mock
    implements _i5.AddressLocalDataSource {
  MockAddressLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AddressModel> getLastAdress() => (super.noSuchMethod(
          Invocation.method(#getLastAdress, []),
          returnValue: Future<_i2.AddressModel>.value(_FakeAddressModel_0()))
      as _i4.Future<_i2.AddressModel>);
  @override
  _i4.Future<void> cacheAdress(_i2.AddressModel? addressToCache) =>
      (super.noSuchMethod(Invocation.method(#cacheAdress, [addressToCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
